apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - image: grafana-service
          imagePullPolicy: Never
          name: nass-grafana-container
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
  selector:
    app: grafana
